Proyecto_Inicial/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('google/', include('google_calendar.urls', namespace='google_calendar')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

google_calendar/urls.py
from django.urls import path
from . import views
app_name = 'google_calendar'

urlpatterns = [
    path('login/', views.google_login, name='google_login'),
    path('callback/', views.google_callback, name='google_callback'),
    path('export/options/<int:calendar_id>/', views.export_options_page, name='export_options'),
    path('export/<int:calendar_id>/', views.export_calendar_events, name='export_calendar_events'),
]

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('signup/', user_signup, name='signup'),
    path('select_calendar/', select_calendar, name='select_calendar'),
    path('create_calendar/', create_calendar, name='create_calendar'),
    path('delete_calendar/<int:calendar_id>/', delete_calendar, name='delete_calendar'),
    path('view_calendar/<int:calendar_id>/<int:type_view>', view_calendar, name='view_calendar'),
    path('edit_calendar/<int:calendar_id>/<int:type_view>', edit_calendar, name='edit_calendar'),
    path('edit_calendar/<int:calendar_id>/<int:type_view>/add_event/', add_event, name='add_event'),
    path('edit_calendar/<int:calendar_id>/clean', clean_calendar, name='clean_calendar'),
    path('edit_calendar/<int:calendar_id>/<int:type_view>/confirm_events', confirm_events, name='confirm_events'),
    path('edit_calendar/<int:calendar_id>/<int:type_view>/undo_events', undo_events, name='undo_events'),
    path('testing', testing, name='testing'),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


# Funcion para guardar la imagen
def event_photo_path(instance, filename):
    return f"event_photos/{filename}"


# Modelo de los eventos predeterminados
class Event(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(default="", blank=True)
    photo = models.ImageField(upload_to=event_photo_path, default='default.png', null=False, blank=False)
    visible = models.BooleanField(default=True)

    REQUIRED_FIELDS = ['name', 'photo_path']

    def __str__(self):
        return self.name


def calendar_photo_path(instance, filename):
    return f"users/{instance.user.id}/{filename}"


# Calendarios bacanes
class Calendar(models.Model):
    name = models.CharField(max_length=30, blank=False, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Añadir alguna imagen en ese el path de DEFAULT antes de ejecutar - B
    photo = models.ImageField(upload_to=calendar_photo_path, default='default.png', blank=True, null=True)

    REQUIRED_FIELDS = ['user', 'name']

    def __str__(self):
        return f"{self.name} de {self.user.username}"


# Conectores y divisores de eventos
# Crear una view específica para
class EventConnector(models.Model):
    DAYS = (
        (0, 'Lunes'),
        (1, 'Martes'),
        (2, 'Miércoles'),
        (3, 'Jueves'),
        (4, 'Viernes'),
        (5, 'Sábado'),
        (6, 'Domingo'),
    )

    GROUPS = (
        (0, 'Mañana'),
        (1, 'Tarde'),
        (2, 'Noche'),
    )

    DIVISIONS = (
        (0, '0'),
        (1, '1'),
        (2, '2'),
    )

    day = models.SmallIntegerField(choices=DAYS)
    group = models.SmallIntegerField(choices=GROUPS)
    division = models.SmallIntegerField(choices=DIVISIONS)
    calendar = models.ForeignKey(Calendar, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    confirmed = models.BooleanField(default=False)

    REQUIRED_FIELDS = ['day', 'group', 'division', 'calendar', 'event']

    def get_days_list(self):
        data = []
        for day in self.DAYS:
            data.append(day[1])
        return data

    def __str__(self):
        return self.event.name

main/forms.py
from django import forms
from main.models import Calendar, EventConnector


class CalendarForm(forms.ModelForm):
    class Meta:
        model = Calendar
        fields = ['name', 'photo']
        labels = {
            'name': 'Nombre',
            'photo': 'Foto',
        }

class AddEventConnectorForm(forms.ModelForm):
    class Meta:
        model = EventConnector
        fields = ['day', 'group', 'division', 'event']
        widgets = {
            'day': forms.DateInput(attrs={'type': 'number', 'min': 0}),
            'group': forms.DateInput(attrs={'type': 'number', 'min': 0}),
            'division': forms.DateInput(attrs={'type': 'number', 'min': 0}),
            'event': forms.DateInput(attrs={'type': 'number', 'min': 0}),
        }

main/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import CalendarForm, AddEventConnectorForm
from .models import *


def index(request):
    return render(request, 'index.html')


def user_login(request):
    if request.user.is_authenticated:
        return redirect('select_calendar')

    context = {
        'form': AuthenticationForm(),
        'message': '',
    }

    if request.method == "POST":
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            context['message'] = 'Usuario y/o Contraseña incorrecta.'
            return render(request, 'testing/login.html', context)
        login(request, user)
        return redirect('select_calendar')
    return render(request, 'testing/login.html', context)


def user_logout(request):
    logout(request)
    return redirect('login')


def user_signup(request):
    if request.user.is_authenticated:
        return redirect('select_calendar')

    context = {
        'form': UserCreationForm(),
        'message': '',
    }

    if request.method == "POST":
        if not UserCreationForm(request.POST).is_valid():
            context['form'] = UserCreationForm(request.POST)
        else:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    password=request.POST['password1']
                )
                user.save()
                context['message'] = '¡Usuario creado correctamente!'
            except ValueError:
                context['message'] = 'Ya existe nombre usuario con este nombre'
    return render(request, 'testing/sign_up.html', context)


@login_required(login_url='login')
def select_calendar(request):
    context = {
        'info': Calendar.objects.filter(user=request.user),
    }
    return render(request, 'testing/calendar_select.html', context)


@login_required(login_url='login')
def create_calendar(request):
    context = {
        'form': CalendarForm(),
        'message': '',
    }
    if request.method == "POST":
        try:
            if len(Calendar.objects.filter(name=request.POST['name'], user=request.user)) == 0:
                calendar = Calendar.objects.create(
                    user=request.user,
                    name=request.POST['name'],
                )
                if len(request.FILES) > 0:
                    calendar.photo = request.FILES['photo']
                calendar.save()
                return redirect('view_calendar', calendar_id=calendar.id, type_view=0)
            else:
                context['message'] = 'Ya tienes un calendario con este nombre.'
        except ValueError:
            pass

    return render(request, 'testing/create_calendar.html', context)


@login_required(login_url='login')
def delete_calendar(request, calendar_id):
    calendar = Calendar.objects.get(id=calendar_id)
    if calendar.user != request.user:
        return redirect('select_calendar')
    calendar.delete()
    return redirect('select_calendar')


@login_required(login_url='login')
def clean_calendar(request, calendar_id):
    # NO SE UTILIZA MAS
    calendar = Calendar.objects.get(id=calendar_id)
    if calendar.user != request.user:
        return redirect('select_calendar')

    events = EventConnector.objects.filter(calendar=calendar)

    events.delete()

    return redirect('edit_calendar', calendar_id=calendar.id, type_view=0)


@login_required(login_url='login')
def view_calendar(request, calendar_id, type_view):
    calendar = Calendar.objects.get(id=calendar_id)
    if calendar.user != request.user:
        return redirect('select_calendar')

    info = {}

    for day in range(len(EventConnector.DAYS)):
        data = []
        for group in range(len(EventConnector.GROUPS)):
            for division in range(len(EventConnector.DIVISIONS)):
                if EventConnector.objects.filter(calendar=calendar, day=day, group=group, division=division,
                                                 confirmed=True).exists():
                    data.append(EventConnector.objects.get(calendar=calendar, day=day, group=group, division=division,
                                                           confirmed=True).event)
                else:
                    data.append(Event.objects.get(name='Default'))

        info[day] = data

    days_info = []
    list_day = EventConnector().get_days_list()

    for i in range(len(list_day)):
        days_info.append([list_day[i], info[i], i + 1])

    context = {
        'calendar_info': calendar,
        'days_info': days_info,
        'type_view': type_view,
        'calendar_comp': '',
        'current_day': '',
    }

    if type_view != 0:
        type_view -= 1
        if type_view < len(days_info):
            context['calendar_comp'] = './components/day_calendar.html'
            context['current_day'] = list_day[type_view]
        else:
            return redirect('view_calendar', calendar_id=calendar.id, type_view=0)
    else:
        context['calendar_comp'] = './components/week_calendar.html'

    return render(request, 'testing/calendar_view.html', context)


@login_required(login_url='login')
def edit_calendar(request, calendar_id, type_view):
    calendar = Calendar.objects.get(id=calendar_id)
    if calendar.user != request.user:
        return redirect('select_calendar')

    info = {}

    for day in range(len(EventConnector.DAYS)):
        data = []
        for group in range(len(EventConnector.GROUPS)):
            for division in range(len(EventConnector.DIVISIONS)):
                if EventConnector.objects.filter(calendar=calendar, day=day, group=group, division=division,
                                                 confirmed=False).exists():
                    data.append(
                        [
                            EventConnector.objects.get(calendar=calendar, day=day, group=group, division=division,
                                                       confirmed=False).event,
                            [day, group, division]
                        ]
                    )
                elif EventConnector.objects.filter(calendar=calendar, day=day, group=group, division=division,
                                                   confirmed=True).exists():
                    data.append(
                        [
                            EventConnector.objects.get(calendar=calendar, day=day, group=group, division=division,
                                                       confirmed=True).event,
                            [day, group, division]
                        ]
                    )
                else:
                    data.append(
                        [Event.objects.get(name='Default'), [day, group, division]]
                    )

        info[day] = data

    days_info = []
    list_day = EventConnector().get_days_list()

    for i in range(len(list_day)):
        days_info.append([list_day[i], info[i], i + 1])

    context = {
        'calendar_info': calendar,
        'type_view': type_view,
        'days_info': days_info,
        'events': Event.objects.filter(visible=True),
        'type_view': type_view,
        'form': AddEventConnectorForm(),
        'delete_event': Event.objects.get(name='Default'),
        'calendar_comp': '',
        'current_day': '',
    }

    if type_view != 0:
        type_view -= 1
        if type_view < len(days_info):
            context['calendar_comp'] = './components/day_edit.html'
            context['current_day'] = list_day[type_view]
        else:
            return redirect('edit_calendar', calendar_id=calendar.id, type_view=0)
    else:
        context['calendar_comp'] = './components/week_edit.html'

    return render(request, 'testing/calendar_edit.html', context)


@login_required(login_url='login')
def confirm_events(request, calendar_id, type_view):
    if Calendar.objects.get(id=calendar_id).user != request.user:
        return redirect('select_calendar')

    data = EventConnector.objects.filter(
        calendar_id=calendar_id,
        confirmed=False,
    )

    for event in data:

        pre_event = EventConnector.objects.filter(
            calendar_id=calendar_id,
            day=event.day,
            group=event.group,
            division=event.division,
            confirmed=True,
        )

        if pre_event.exists():
            pre_event.delete()

        event.confirmed = True
        event.save()

    return redirect('view_calendar', calendar_id=calendar_id, type_view=type_view)


@login_required(login_url='login')
def undo_events(request, calendar_id, type_view):
    if Calendar.objects.get(id=calendar_id).user != request.user:
        return redirect('select_calendar')

    data = EventConnector.objects.filter(
        calendar_id=calendar_id,
        confirmed=False,
    )

    for event in data:
        event.delete()

    return redirect('edit_calendar', calendar_id=calendar_id, type_view=type_view)


@login_required(login_url='login')
def add_event(request, calendar_id, type_view):
    if Calendar.objects.get(id=calendar_id).user != request.user:
        return redirect('select_calendar')

    try:
        pre_event = EventConnector.objects.filter(
            calendar_id=calendar_id,
            day=request.POST['day'],
            group=request.POST['group'],
            division=request.POST['division'],
            confirmed=False,
        )

        if pre_event.exists():
            pre_event.delete()

        connector = EventConnector.objects.create(
            day=request.POST['day'],
            group=request.POST['group'],
            division=request.POST['division'],
            calendar=Calendar.objects.get(id=calendar_id),

main/templates/testing/calendar.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/testing.css' %}">
    <link rel="stylesheet" href="{% static 'css/testing_calendar_elements.css' %}">
{% endblock %}

{% block left-bar %}
	<p>{{ calendar_info }}</p>
{% endblock %}

{% block right-bar %}
    <p><a href="{% url 'edit_calendar' calendar_info.id %}">Editar</a></p>
	<p><a href="{% url 'select_calendar' %}">Volver al Inicio</a></p>
{% endblock %}

{% block content %}
	<div class="calendar-container centered">
        {% for day in days_info %}
        	<div class="calendar-day-block">
                <p class="calendar-day-title">{{ day.0 }}</p>
                {% for event in day.1 %}
                    <p class="calendar-block">
                        <img src="{% static event.photo_path %}" alt="{{ event }}" height="32px" width="32px">
                    </p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/testing/calendar_edit.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/testing_calendar_edit.css' %}">
    <link rel="stylesheet" href="{% static 'css/testing_calendar_elements.css' %}">
{% endblock %}

{% block left-bar %}
    <div class="me-3">{{ calendar_info }}</div>
{% endblock %}

{% block right-bar %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end me-2 mb-0">
            <li class="page-item"><a class="page-link bg-primary text-light"
                                     href="{% url 'undo_events' calendar_info.id type_view %}">Deshacer
                cambios ↩️</a>
            </li>
            <li class="page-item"><a class="page-link bg-primary text-light"
                                     href="{% url 'confirm_events' calendar_info.id type_view %}">Confirmar 👌</a>
            </li>
            <li class="page-item"><a class="page-link bg-primary text-light"
                                     href="{% url 'view_calendar' calendar_info.id type_view %}">Volver 🔁</a>
            </li>
        </ul>
    </nav>

{% endblock %}

{% block content %}
    <div class="main-calendar-container centered">
        {% include calendar_comp %}
    </div>
    <div class="edit-container centered">
        <p class="event-element m-1">Imágenes 🖼️</p>
        <div class="d-flex align-center mb-1">
            <form class="my-2 mx-2 form-search-event">
                <input id="form-search" class="form-control" type="search" placeholder="Buscar" onkeyup="Search()">
            </form>
            <p id="delete-block" class="event-block test-danger rounded"
               data-id="{{ delete_event.id }}"
               data-name="{{ delete_event.name }}"
               draggable="true">
                <img class="rounded text-bg-danger p-2" src="{% static 'images/erase_icon.png' %}" alt="" height="50px"
                     width="50px">
            </p>
        </div>
        <ul class="row row-cols-auto p-3 w-100 justify-content-center list-events">
            {% for event in events %}
                <li class="event-element event-block col text-decoration-none list-group-item m-2 p-1"
                    data-id="{{ event.id }}"
                    data-name="{{ event.name }}"
                    draggable="true">
                    <img class="rounded mx-auto d-block" src="{{ event.photo.url }}" alt="{{ event.name }}"
                         height="96px" width="96px">
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block hidden %}
    <form action="{% url 'add_event' calendar_info.id type_view %}" method="POST" id="form-event_connector">
        {% csrf_token %}
        {{ form }}
    </form>
    <script src="{% static 'js/testing_edit_calendar.js' %}"></script>
{% endblock %}

main/templates/testing/calendar_select.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/testing.css' %}">
    <link rel="stylesheet" href="{% static 'css/testing_select_calendar.css' %}">
{% endblock %}

{% block left-bar %}
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active me-3" aria-current="page" href="{% url 'create_calendar' %}">Crear Agenda 🗓️</a>
        </li>
    </ul>
{% endblock %}

{% block right-bar %}
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active me-3" aria-current="page" href="{% url 'logout' %}">Cerrar Sesión 🏃🚪</a>
        </li>
    </ul>
{% endblock %}

{% block content %}

    {% for calendar in info %}
        <div class="view-calendar-container border">
            <div class="view-calendar-container">
                <div class="view-calendar-container img-border">
                    <a href="{% url 'view_calendar' calendar.id 0 %}">
                        <img class="hexagon" src="{{ calendar.photo.url }}" alt="" height="128px" width="128px">
                    </a>
                </div>
                <p>{{ calendar.name }}</p>
                <a href="{% url 'delete_calendar' calendar.id %}" class="btn btn-danger active px-2"
                   aria-current="page">
                    Borrar ⛔</a>
            </div>
        </div>
    {% empty %}
        <div class="card">
            <div class="card-header text-center">
                🐝 ABEJJAS 🐝
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">¡ Hola Abejita 👋😊 !</h5>
                <p class="card-text">Para comenzar, crea una agenda en el botón "Crear agenda 🗓️" y podrás diseñar tu agenda semanal.
                    Y si ya tienes una, sigue diseñando :) , ¡¡ ánimo !!.</p>
            </div>
        </div>
    {% endfor %}

{% endblock %}

main/templates/testing/calendar_view.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/testing.css' %}">
    <link rel="stylesheet" href="{% static 'css/testing_calendar_elements.css' %}">
{% endblock %}

{% block left-bar %}
    <div class="me-3">{{ calendar_info }}</div>
{% endblock %}

{% block right-bar %}
    <ul class="nav nav-pills d-flex flex-wrap justify-content-center align-items-center">
        <li class="nav-item me-3">
            <a href="{% url 'edit_calendar' calendar_info.id type_view %}" class="nav-link active active"
               aria-current="page">Editar ✏️</a>
        </li>
        <li class="nav-item me-3">
            <a href="{% url 'google_calendar:export_options' calendar_info.id %}" class="nav-link active btn-success">Exportar a Google 🚀</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'select_calendar' %}" class="nav-link active active" aria-current="page"> Volver al
                Inicio ⬅️</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    {% include calendar_comp %}
{% endblock %}

main/templates/testing/create_calendar.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/testing.css' %}">
{% endblock %}

{% block left-bar %}
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a href="{% url 'select_calendar' %}" class="btn btn-primary active me-3" aria-current="page"> Volver al
                Inicio ⬅️</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <form action="{% url 'create_calendar' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h1 class="h3 mb-2 fw-normal text-center"> 📍 Crear agenda 📍</h1>
        <div class="mb-3">
            <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label }}</label>
            <input type="text" name="name" class="form-control"
                   maxlength="30" required id="id_name">
            <div id="error-div" class="invalid-feedback">
                {{ message }}
            </div>
        </div>
        <div class="mb-3">
            <label for="{{ form.photo.id_for_label }}" class="form-label">{{ form.photo.label }}</label>
            <p class="form-text">¡Seleciona una imagen para tu agenda!</p>
            <input class="form-control" type="file" name="photo" accept="image/*" id="id_photo">
        </div>
        <button type="submit" class="btn btn-success w-100 mt-3">Crear</button>
    </form>
{% endblock %}

{% block hidden %}
    <script src="{% static 'js/create_calendar.js' %}"></script>
{% endblock %}

main/templates/testing/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
    <div class="form-signin w-100 m-auto">
        <form action="{% url 'login' %}" method="POST" class="card-body">
            <h1 class="h3 mb-3 fw-normal text-center"> 📋 Iniciar sesión 📋</h1>
            {% csrf_token %}
            {# Form modificado #}
            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}</label>
                <input type="text" name="username" class="form-control" autofocus autocapitalize="none"
                       autocomplete="username" maxlength="150" required id="username">
                {{ form.username.errors }}
            </div>
            <div class="mb-3">
                <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
                <input type="password" name="password" autocomplete="current_password" class="form-control" required
                       id="password">
                {{ form.password.errors }}
                <div id="error-div" class="invalid-feedback">
                    {{ message }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary w-100 py-2"> 👉 Iniciar sesión 👈</button>
            <p class="form-text text-center mt-3"> 🚩 ¿Todavía no tienes cuenta? 👉 <a href="{% url 'signup' %}"
                                                                                class="link-underline link-underline-opacity-0">Regístrate</a>
            </p>
            <p class="text-center">© 2025 ABEJJAS</p>
        </form>
    </div>
{% endblock %}

{% block hidden %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}
----------------------------------------------------------------------------------------------------
<div class="card">
    <form action="{% url 'login' %}" method="POST" class="card-body">
        {% csrf_token %}
        {# Form modificado #}
        <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}</label>
            <input type="text" name="username" class="form-control" autofocus autocapitalize="none"
                   autocomplete="username" maxlength="150" required id="username">
            {{ form.username.errors }}
        </div>
        <div class="mb-3">
            <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
            <input type="password" name="password" autocomplete="current_password" class="form-control" required
                   id="password">
            {{ form.password.errors }}
        </div>
        <button type="submit" class="btn btn-primary">Iniciar sesión</button>

    </form>
</div>
{{ message }}
<a href="{% url 'signup' %}" class="btn btn-info" role="button">Regístrate</a>

<form>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

main/templates/testing/sign_up.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}
    <div class="form-signup w-100 m-auto p-3">
        <form action="{% url 'signup' %}" method="POST" class="card-body">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Registrarse</h1>
            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                <div class="form-text mb-1">{{ form.username.help_text }}</div>
                <input type="text" name="username" class="form-control" autofocus autocapitalize="none"
                       autocomplete="username" maxlength="150" required id="username">
                <div id="user-error" class="form-text invalid-feedback">
                    {{ form.username.errors }}
                </div>
            </div>
            <div class="mb-3">
                <label for="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
                <div class="form-text mb-1">{{ form.password1.help_text }}</div>
                <input type="password" name="password1" autocomplete="new_password" class="form-control" required
                       id="password1">
                <div id='pass1-error' class="form-text invalid-feedback">
                    {{ form.password1.errors }}
                </div>
            </div>
            <div class="mb-3">
                <label for="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
                <div class="form-text mb-1">{{ form.password2.help_text }}</div>
                <input type="password" name="password2" autocomplete="new_password" class="form-control" required
                       id="password2">
                <div id="pass2-error" class="form-text invalid-feedback">
                    {{ form.password2.errors }}
                </div>
            </div>
            <p class="text-center link-success text-decoration-none">{{ message }}</p>
            <div class="form-buttons d-flex">
                <button type="submit" class="btn btn-primary w-50">❗ Regístrarse ❗</button>
                <p class="form-text m-0 mt-2 h-auto w-50 text-center">
                    ¿Ya tienes cuenta?
                    <a href="{% url 'login' %}" class="text-decoration-none p-auto">
                        Inicia sesión
                    </a>
                </p>
            </div>
        </form>
    </div>
{% endblock %}

{% block hidden %}
    <script src="{% static 'js/signup.js' %}"></script>
{% endblock %}